apiVersion: v1
kind: Secret
metadata:
  name: bullpawn-backend
  namespace: bullpawn-staging
type: Opaque
data:
  private-key: <BASE64_ENCODED_PRIVATE_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: bullpawn-contracts
  namespace: bullpawn-staging
type: Opaque
data:
  private-key: <BASE64_ENCODED_PRIVATE_KEY>
