{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bullpawn.fullname" . }}
  labels:
    {{- include "bullpawn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "bullpawn.selectorLabels" . | nindent 4 }}
{{- end }}
