name: Deploy Smart Contracts

on:
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  ZKSYNC_RPC_URL: "https://sepolia.era.zksync.dev"
  ZKSYNC_CHAIN_ID: "300"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-contracts:
    name: Deploy Smart Contracts to zkSync
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd contracts
        npm install

    - name: Build contracts
      run: |
        cd contracts
        npm run build

    - name: Deploy contracts to zkSync
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        USDT_CONTRACT_ADDRESS: "0x5C221E77624690fff6dd7412D22CCeB3F3167453"
        CHAINLINK_ETH_USD: "0xfEefF7c3fB57d18C5C6Cdd71e45D2D0b4F9377bF"
        CHAINLINK_BTC_USD: "0x95Bc57e794aeb02E4a16eff406147f3ce2531F83"
      run: |
        cd contracts
        npm run deploy

    - name: Extract contract addresses
      id: extract-addresses
      run: |
        cd contracts
        # Extract addresses from the deployment artifacts
        PAWN_ADDRESS=$(jq -r '.address' artifacts-zk/PawnContract.json)
        ORACLE_ADDRESS=$(jq -r '.address' artifacts-zk/MultiOracle.json)
        ETH_FEED_ADDRESS=$(jq -r '.address' artifacts-zk/ETHPriceFeed.json)
        BTC_FEED_ADDRESS=$(jq -r '.address' artifacts-zk/BTCPriceFeed.json)
        
        # Set outputs for use in subsequent steps
        echo "PAWN_CONTRACT_ADDRESS=${PAWN_ADDRESS}" >> $GITHUB_OUTPUT
        echo "MULTI_ORACLE_ADDRESS=${ORACLE_ADDRESS}" >> $GITHUB_OUTPUT
        echo "ETH_PRICE_FEED_ADDRESS=${ETH_FEED_ADDRESS}" >> $GITHUB_OUTPUT
        echo "BTC_PRICE_FEED_ADDRESS=${BTC_FEED_ADDRESS}" >> $GITHUB_OUTPUT